### PR TITLE
Minor: fix for OneDAL4PY DBSCAN

### PR DESCRIPTION
**Pull request by samir-nasibli**
# Description
TBD
maybe it make sense remove: https://github.com/intel/scikit-learn-intelex/blob/895673751b509eb2fba0793bf3f82dd08cd35bb7/deselected_tests.yaml#L110

### CODE REVIEW

**Comment by icfaust** [comment]
If this passes private CI, I will review to merge.

**Comment by samir-nasibli** [comment]
> If this passes private CI, I will review to merge.

Before the merge I would like to have perf validation as well for dbscan, since here some conversions happen.
Also maybe make sense remove mentioned in the description DBSCAN test case.

**Comment by syakov-intel** [comment]
@samir-nasibli what needs to be done to make it ready for review?

**Comment by samir-nasibli** [comment]
changes are outdated and not needed. Currently logic is wrong, no need to convert intc data type.

**Pull request closed without merging**
