### PR TITLE
try to skip only gpu spmd tests

### PR DESCRIPTION
**Pull request by JuliaRS**
## Description

_Add a comprehensive description of proposed changes_

_List associated issue number(s) if exist(s): #6 (for example)_

_Documentation PR (if needed): #1340 (for example)_

_Benchmarks PR (if needed): https://github.com/IntelPython/scikit-learn_bench/pull/155 (for example)_

---

PR should start as a draft, then move to ready for review state after CI is passed and all applicable checkboxes are closed.
This approach ensures that reviewers don't spend extra time asking for regular requirements.

You can remove a checkbox as not applicable only if it doesn't relate to this PR in any way.
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code change is expected to affect performance (or justification should be self-evident).

Checklist to comply with **before moving PR from draft**:

**PR completeness and readability**

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [x] I have added a respective label(s) to PR if I have a permission for that.
- [x] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [x] I have run it locally and tested the changes extensively.
- [x] All CI jobs are green or I have provided justification why they aren't.
- [x] I have extended testing suite if new functionality was introduced in this PR.

**Performance**

- [x] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [x] I have provided justification why performance has changed or why changes are not expected.
- [x] I have provided justification why quality metrics have changed or why changes are not expected.
- [x] I have extended benchmarking suite and provided corresponding scikit-learn_bench PR if new measurable functionality was introduced in this PR.

### CODE REVIEW

**Comment by icfaust** [comment]
@JuliaRS please add a description, I am trying to figure out how checking for dpctl makes skip only gpu (what about dpnp too?)

**Comment by JuliaRS** [comment]
```
(build_sklearnex) jroznova@sdpdal630226:/export/users/jroznova/scikit-learn-intelex$ python tests/run_examples.py
Starting examples validation
DAAL version: (2025, 'P', 200)
GPU device available: False

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/spmd_chunks_read.py
15:20:42        PASSED  spmd_chunks_read.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/sgd_logistic_loss.py
15:20:43        PASSED  sgd_logistic_loss.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/pca_spmd.py
15:20:45        PASSED  pca_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/svd_streaming.py
15:20:46        PASSED  svd_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/logitboost.py
15:20:47        PASSED  logitboost.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/low_order_moms_spmd.py
15:20:49        PASSED  low_order_moms_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/svm.py
15:20:55        PASSED  svm.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/gradient_boosted_classification.py
15:20:57        PASSED  gradient_boosted_classification.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/naive_bayes.py
15:20:58        PASSED  naive_bayes.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/univariate_outlier.py
15:20:59        PASSED  univariate_outlier.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/log_reg_dense.py
15:21:00        PASSED  log_reg_dense.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/covariance.py
15:21:01        PASSED  covariance.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/normalization_zscore.py
15:21:01        PASSED  normalization_zscore.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/em_gmm.py
15:21:02        PASSED  em_gmm.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/qr_streaming.py
15:21:04        PASSED  qr_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_tree_classification_traverse.py
15:21:05        PASSED  decision_tree_classification_traverse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/linear_regression.py
15:21:06        PASSED  linear_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/lasso_regression.py
15:21:07        PASSED  lasso_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_tree_regression.py
15:21:08        PASSED  decision_tree_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/kmeans_spmd.py
15:21:10        PASSED  kmeans_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/pca.py
15:21:10        PASSED  pca.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/svm_multiclass.py
15:21:12        PASSED  svm_multiclass.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/cholesky.py
15:21:12        PASSED  cholesky.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/svd_spmd.py
15:21:14        PASSED  svd_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/ridge_regression_spmd.py
15:21:16        PASSED  ridge_regression_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/sgd_mse.py
15:21:17        PASSED  sgd_mse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/kmeans.py
15:21:18        PASSED  kmeans.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/implicit_als.py
15:21:19        PASSED  implicit_als.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_forest_classification_hist.py
15:21:20        PASSED  decision_forest_classification_hist.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/low_order_moms_dense.py
15:21:20        PASSED  low_order_moms_dense.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_forest_classification_traverse.py
15:21:22        PASSED  decision_forest_classification_traverse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/linear_regression_streaming.py
15:21:23        PASSED  linear_regression_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/distributions_bernoulli.py
15:21:24        PASSED  distributions_bernoulli.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/bf_knn_classification.py
15:21:24        PASSED  bf_knn_classification.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/pivoted_qr.py
15:21:25        PASSED  pivoted_qr.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_forest_regression_traverse.py
15:21:26        PASSED  decision_forest_regression_traverse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/quantiles.py
15:21:27        PASSED  quantiles.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/naive_bayes_streaming.py
15:21:28        PASSED  naive_bayes_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/log_reg_binary_dense.py
15:21:29        PASSED  log_reg_binary_dense.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/correlation_distance.py
15:21:30        PASSED  correlation_distance.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/dbscan.py
15:21:31        PASSED  dbscan.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/sorting.py
15:21:32        PASSED  sorting.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/qr_spmd.py
15:21:34        PASSED  qr_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/association_rules.py
15:21:37        PASSED  association_rules.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_forest_regression_default_dense.py
15:21:38        PASSED  decision_forest_regression_default_dense.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/adagrad_mse.py
15:21:39        PASSED  adagrad_mse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/ridge_regression_streaming.py
15:21:40        PASSED  ridge_regression_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/linear_regression_spmd.py
15:21:41        PASSED  linear_regression_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/stump_regression.py
15:21:42        PASSED  stump_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/ridge_regression.py
15:21:43        PASSED  ridge_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/low_order_moms_streaming.py
15:21:44        PASSED  low_order_moms_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/qr.py
15:21:45        PASSED  qr.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/distributions_uniform.py
15:21:46        PASSED  distributions_uniform.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/svd.py
15:21:47        PASSED  svd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/covariance_streaming.py
15:21:48        PASSED  covariance_streaming.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/saga.py
15:21:50        PASSED  saga.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/normalization_minmax.py
15:21:51        PASSED  normalization_minmax.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/readcsv.py
15:21:51        PASSED  readcsv.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/pca_transform.py
15:21:52        PASSED  pca_transform.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_forest_classification_default_dense.py
15:21:53        PASSED  decision_forest_classification_default_dense.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/dbscan_spmd.py
15:21:55        PASSED  dbscan_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_tree_regression_traverse.py
15:21:56        PASSED  decision_tree_regression_traverse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/naive_bayes_spmd.py
15:21:57        PASSED  naive_bayes_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/gradient_boosted_regression_traverse.py
15:21:59        PASSED  gradient_boosted_regression_traverse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/distributions_normal.py
15:21:59        PASSED  distributions_normal.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/covariance_spmd.py
15:22:01        PASSED  covariance_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/kdtree_knn_classification.py
15:22:02        PASSED  kdtree_knn_classification.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/stump_classification.py
15:22:03        PASSED  stump_classification.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/gradient_boosted_classification_traverse.py
15:22:04        PASSED  gradient_boosted_classification_traverse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_tree_classification.py
15:22:05        PASSED  decision_tree_classification.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/lbfgs_mse.py
15:22:06        PASSED  lbfgs_mse.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/bacon_outlier.py
15:22:07        PASSED  bacon_outlier.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/cosine_distance.py
15:22:08        PASSED  cosine_distance.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/multivariate_outlier.py
15:22:09        PASSED  multivariate_outlier.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/adaboost.py
15:22:10        PASSED  adaboost.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/lbfgs_cr_entr_loss.py
15:22:11        PASSED  lbfgs_cr_entr_loss.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/decision_forest_regression_hist.py
15:22:12        PASSED  decision_forest_regression_hist.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/brownboost.py
15:22:13        PASSED  brownboost.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/elastic_net.py
15:22:13        PASSED  elastic_net.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/daal4py/gradient_boosted_regression.py
15:22:15        PASSED  gradient_boosted_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/pca_spmd.py
15:22:15        SKIPPED pca_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/knn_bf_regression_spmd.py
15:22:15        SKIPPED knn_bf_regression_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/basic_statistics_spmd.py
15:22:15        SKIPPED basic_statistics_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_covariance_spmd.py
15:22:15        SKIPPED incremental_covariance_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/kmeans_spmd.py
15:22:15        SKIPPED kmeans_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_pca_dpctl.py
15:22:15        SKIPPED incremental_pca_dpctl.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/knn_bf_classification_spmd.py
15:22:15        SKIPPED knn_bf_classification_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_covariance.py
15:22:16        PASSED  incremental_covariance.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/dbscan_array_api.py
15:22:17        PASSED  dbscan_array_api.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_pca.py
15:22:18        PASSED  incremental_pca.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/verbose_mode.py
15:22:19        PASSED  verbose_mode.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/logistic_regression_spmd.py
15:22:19        SKIPPED logistic_regression_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/patch_sklearn.py
15:22:20        PASSED  patch_sklearn.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/n_jobs.py
15:22:21        PASSED  n_jobs.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/random_forest_classifier_spmd.py
15:22:21        SKIPPED random_forest_classifier_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/random_forest_classifier_dpctl.py
15:22:21        SKIPPED random_forest_classifier_dpctl.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/linear_regression_spmd.py
15:22:21        SKIPPED linear_regression_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_linear_regression.py
15:22:22        PASSED  incremental_linear_regression.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_basic_statistics_dpctl.py
15:22:22        SKIPPED incremental_basic_statistics_dpctl.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_basic_statistics.py
15:22:23        PASSED  incremental_basic_statistics.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/random_forest_regressor_dpnp.py
15:22:23        SKIPPED random_forest_regressor_dpnp.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/dbscan_spmd.py
15:22:23        SKIPPED dbscan_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/covariance_spmd.py
15:22:23        SKIPPED covariance_spmd.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/incremental_linear_regression_dpctl.py
15:22:23        SKIPPED incremental_linear_regression_dpctl.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/knn_bf_classification_dpnp.py
15:22:23        SKIPPED knn_bf_classification_dpnp.py

##### /localdisk2/mkl/jroznova/scikit-learn-intelex/examples/sklearnex/random_forest_regressor_spmd.py
15:22:23        SKIPPED random_forest_regressor_spmd.py
106/106 examples passed/skipped
```

**Comment by JuliaRS** [comment]
I found that the problem not in the same naming.
The problem in check_library for 'dpctl'.

**Comment by JuliaRS** [comment]
https://ecmd.jf.intel.com/commander/link/jobDetails/jobs/efbbcb4a-1fae-f1a7-b0d1-a4bf010d0e2d?linkPageType=jobDetails&objectLocator=/jobs/efbbcb4a-1fae-f1a7-b0d1-a4bf010d0e2d&tabGroup=stepTableHeader&s=Jobs

**Review by ethanglaser — APPROVED** [review]
LGTM, skips no longer occur, nice work on this

**Pull request merged**
