### PR TITLE
feature: new rng engines support

### PR DESCRIPTION
**Pull request by Alexandr-Solovev**
## Description

PR is necessary to enable new rng engines on oneDAL side. See https://github.com/uxlfoundation/oneDAL/pull/2968

---

**PR completeness and readability**

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/uxlfoundation/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [x] I have added a respective label(s) to PR if I have a permission for that.
- [x] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [x] I have run it locally and tested the changes extensively.
- [x] All CI jobs are green or I have provided justification why they aren't.
- [x] I have extended testing suite if new functionality was introduced in this PR.

### CODE REVIEW

**Review by avolkov-intel — APPROVED** [review]
LGTM, but wait for green CI before merge

**Review by david-cortes-intel — APPROVED** [review]
Error in the CI is not related to the changes here. Let's merge this and wait for green CI on the oneDAL side.

**Pull request merged**
